# Deploy Script for JobAI Search
# Uses Windows Task Scheduler to keep Node.js running after SSH disconnect

param(
    [string]$AppDir = "C:\AI-Working-Seacrh",
    [string]$Port = "3000"
)

$ErrorActionPreference = "Stop"

Set-Location $AppDir

Write-Host "========================================"
Write-Host "  JobAI Auto Deploy"
Write-Host "========================================"
Write-Host "Time: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
Write-Host ""

# Step 1: Pull latest code
Write-Host "[1/6] Pulling latest code..." -ForegroundColor Cyan

$gitToken = $env:GH_DEPLOY_TOKEN
if (-not $gitToken) {
    Write-Host "ERROR: GH_DEPLOY_TOKEN not set!" -ForegroundColor Red
    exit 1
}

& git config --local --unset credential.helper 2>&1 | Out-Null
& git config --local credential.helper "" 2>&1 | Out-Null

$repoUrl = "https://${gitToken}@github.com/RaijiTRW/AI-Working-Seacrh.git"
& git remote set-url origin $repoUrl 2>&1 | Out-Null

Write-Host "Fetching and resetting..."
& git fetch origin main 2>&1 | Out-Host
& git reset --hard origin/main 2>&1 | Out-Host

$newVersion = & git rev-parse --short HEAD
Write-Host "Deploying version: $newVersion"

# Step 2: Stop ALL Node.js processes
Write-Host ""
Write-Host "[2/6] Stopping Node.js..." -ForegroundColor Cyan

# Kill by port first
Get-NetTCPConnection -LocalPort $Port -ErrorAction SilentlyContinue | ForEach-Object {
    $proc = Get-Process -Id $_.OwningProcess -ErrorAction SilentlyContinue
    if ($proc) {
        Write-Host "  Killing process $($proc.Id) on port $Port..."
        Stop-Process -Id $_.OwningProcess -Force -ErrorAction SilentlyContinue
    }
}

# Kill all node processes
Get-Process -Name "node" -ErrorAction SilentlyContinue | ForEach-Object {
    Write-Host "  Killing node process $($_.Id)..."
    Stop-Process -Id $_.Id -Force -ErrorAction SilentlyContinue
}

Start-Sleep -Seconds 3

# Step 3: Install dependencies
Write-Host ""
Write-Host "[3/6] Installing dependencies..." -ForegroundColor Cyan

if (Test-Path "node_modules") {
    Remove-Item -Recurse -Force "node_modules" -ErrorAction SilentlyContinue
    Start-Sleep -Seconds 1
}

& npm ci 2>&1 | Out-Host
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: npm ci failed!" -ForegroundColor Red
    exit 1
}
Write-Host "Dependencies installed"

# Step 4: Build
Write-Host ""
Write-Host "[4/6] Building..." -ForegroundColor Cyan

if (Test-Path ".next") {
    Remove-Item -Recurse -Force ".next" -ErrorAction SilentlyContinue
    Start-Sleep -Seconds 1
}

$env:PORT = $Port
& npm run build 2>&1 | Out-Host
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: Build failed!" -ForegroundColor Red
    exit 1
}
Write-Host "Build completed"

$buildIdPath = "$AppDir\.next\BUILD_ID"
if (Test-Path $buildIdPath) {
    $newBuildId = Get-Content $buildIdPath
    Write-Host "New BUILD_ID: $newBuildId"
}

# Step 5: Create persistent launcher script
Write-Host ""
Write-Host "[5/6] Creating persistent launcher..." -ForegroundColor Cyan

$launcherScript = @"
# Persistent Node.js Launcher for JobAI Search
# Generated by deploy.ps1 - survives SSH disconnect

`$ErrorActionPreference = "Stop"

# Set environment
`$env:NODE_ENV = "production"
`$env:PORT = "$Port"

# Paths
`$nodeExe = "C:\Program Files\nodejs\node.exe"
`$nextBin = "$AppDir\node_modules\next\dist\bin\next"
`$workingDir = "$AppDir"

# Start Node.js
Write-Host "Starting Node.js at `(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')`"
`$process = Start-Process -FilePath `$nodeExe -ArgumentList "next start" -WorkingDirectory `$workingDir -WindowStyle Hidden -PassThru

# Save PID
`$process.Id | Out-File -FilePath "$AppDir\node.pid" -Encoding UTF8
Write-Host "Started Node.js with PID: `$(`$process.Id)"

# Keep this script running to maintain process tree
try {
    `$proc = Get-Process -Id `$process.Id -ErrorAction Stop
    while (`$proc -and -not `$proc.HasExited) {
        Start-Sleep -Seconds 5
        `$proc.Refresh()
    }
} catch {
    # Process ended
}
Write-Host "Node.js process exited at `(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')`"
"@

$launcherPath = "$AppDir\scripts\run-node.ps1"
Set-Content -Path $launcherPath -Value $launcherScript -Encoding UTF8

# Step 6: Start via Task Scheduler (survives SSH)
Write-Host ""
Write-Host "[6/6] Starting Node.js via Task Scheduler..." -ForegroundColor Cyan

$taskName = "JobAI-Node-Runner"

# Delete existing task if exists
schtasks /Delete /TN $taskName /F 2>&1 | Out-Null

# Create task that runs immediately and keeps running
$taskCmd = "powershell -NoProfile -ExecutionPolicy Bypass -File `"$launcherPath`""

schtasks /Create /TN $taskName /TR $taskCmd /SC ONCE /ST 00:00 /F 2>&1 | Out-Null
schtasks /Run /TN $taskName 2>&1 | Out-Null

Write-Host "  Task created and started"
Write-Host "  Waiting for Node.js to start..."
Start-Sleep -Seconds 10

# Step 7: Health check
Write-Host ""
Write-Host "[7/7] Health check..." -ForegroundColor Cyan

$healthy = $false
for ($i = 1; $i -le 30; $i++) {
    try {
        $response = Invoke-WebRequest -Uri "http://127.0.0.1:${Port}/api/version" -UseBasicParsing -TimeoutSec 5
        if ($response.StatusCode -eq 200) {
            $version = $response.Content | ConvertFrom-Json
            Write-Host "  OK! Site is running" -ForegroundColor Green
            Write-Host "  Version: $($version.version)" -ForegroundColor Cyan
            $healthy = $true
            break
        }
    } catch {
        Write-Host "  Attempt $i/30..."
        Start-Sleep -Seconds 2
    }
}

if (-not $healthy) {
    Write-Host "ERROR: Health check failed!" -ForegroundColor Red
    exit 1
}

# Update .version file
Set-Content -Path "$AppDir\.version" -Value $newVersion -Encoding UTF8

Write-Host ""
Write-Host "========================================"
Write-Host "  Deploy Complete!"
Write-Host "========================================"
Write-Host "Version: $newVersion"
Write-Host "Node.js is running via Task Scheduler"
Write-Host "Site will stay up after SSH disconnect"
Write-Host "Time: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
Write-Host "========================================"

# Cleanup git credentials
& git config --local --unset credential.helper 2>&1 | Out-Null

exit 0
