# Deploy Script that keeps Node.js running
# Uses nohup equivalent for Windows to survive SSH disconnect

param(
    [string]$AppDir = "C:\AI-Working-Seacrh"
)

$ErrorActionPreference = "Stop"

Set-Location $AppDir

Write-Host "========================================"
Write-Host "  JobAI Deploy (Persistent)"
Write-Host "========================================"
Write-Host "Time: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
Write-Host ""

# Step 1: Pull latest code
Write-Host "[1/5] Pulling latest code..." -ForegroundColor Cyan

$gitToken = $env:GH_DEPLOY_TOKEN
if (-not $gitToken) {
    Write-Host "ERROR: GH_DEPLOY_TOKEN not set!" -ForegroundColor Red
    exit 1
}

& git config --local --unset credential.helper 2>&1 | Out-Null
& git config --local credential.helper "" 2>&1 | Out-Null

$repoUrl = "https://${gitToken}@github.com/RaijiTRW/AI-Working-Seacrh.git"
& git remote set-url origin $repoUrl 2>&1 | Out-Null

Write-Host "Fetching and resetting..."
& git fetch origin main 2>&1 | Out-Host
& git reset --hard origin/main 2>&1 | Out-Host

$newVersion = & git rev-parse --short HEAD
Write-Host "Deploying version: $newVersion"

# Step 2: Stop existing Node.js
Write-Host ""
Write-Host "[2/5] Stopping Node.js..." -ForegroundColor Cyan

# Kill by PID file first
$pidFile = "$AppDir\node.pid"
if (Test-Path $pidFile) {
    try {
        $pid = Get-Content $pidFile
        $proc = Get-Process -Id $pid -ErrorAction SilentlyContinue
        if ($proc) {
            Write-Host "  Killing PID $pid (from node.pid)..."
            Stop-Process -Id $pid -Force -ErrorAction SilentlyContinue
            Start-Sleep -Seconds 2
        }
    } catch {}
    Remove-Item $pidFile -Force -ErrorAction SilentlyContinue
}

# Kill all node processes
Get-Process -Name "node" -ErrorAction SilentlyContinue | ForEach-Object {
    Write-Host "  Killing node process $($_.Id)..."
    Stop-Process -Id $_.Id -Force -ErrorAction SilentlyContinue
}

# Kill by port
Get-NetTCPConnection -LocalPort 3000 -ErrorAction SilentlyContinue | ForEach-Object {
    $proc = Get-Process -Id $_.OwningProcess -ErrorAction SilentlyContinue
    if ($proc) {
        Write-Host "  Killing process $($proc.Id) on port 3000"
        Stop-Process -Id $_.OwningProcess -Force -ErrorAction SilentlyContinue
    }
}

Start-Sleep -Seconds 5

# Step 3: Install dependencies
Write-Host ""
Write-Host "[3/5] Installing dependencies..." -ForegroundColor Cyan

if (Test-Path "node_modules") {
    Remove-Item -Recurse -Force "node_modules" -ErrorAction SilentlyContinue
    Start-Sleep -Seconds 1
}

& npm ci 2>&1 | Out-Host
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: npm ci failed!" -ForegroundColor Red
    exit 1
}
Write-Host "Dependencies installed"

# Step 4: Build
Write-Host ""
Write-Host "[4/5] Building..." -ForegroundColor Cyan

if (Test-Path ".next") {
    Remove-Item -Recurse -Force ".next" -ErrorAction SilentlyContinue
    Start-Sleep -Seconds 1
}

$env:PORT = "3000"
& npm run build 2>&1 | Out-Host
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: Build failed!" -ForegroundColor Red
    exit 1
}
Write-Host "Build completed"

$buildIdPath = "$AppDir\.next\BUILD_ID"
if (Test-Path $buildIdPath) {
    $newBuildId = Get-Content $buildIdPath
    Write-Host "New BUILD_ID: $newBuildId"
}

# Step 5: Start Node.js in background (persistent)
Write-Host ""
Write-Host "[5/5] Starting Node.js (persistent)..." -ForegroundColor Cyan

# Create startup script that runs in background
$startScript = @"
# Start-Node.ps1 - Generated by deploy script
# This keeps Node.js running after SSH disconnect

`$env:NODE_ENV = "production"
`$env:PORT = "3000"

`$nodeExe = "C:\Program Files\nodejs\node.exe"
`$nextBin = "C:\AI-Working-Seacrh\node_modules\next\dist\bin\next"
`$nextStart = "`$nextBin start"

# Start process and save PID
`$process = Start-Process -FilePath `$nodeExe -ArgumentList `$nextStart -WorkingDirectory "C:\AI-Working-Seacrh" -WindowStyle Hidden -PassThru

`$process.Id | Out-File -FilePath "C:\AI-Working-Seacrh\node.pid" -Encoding UTF8

Write-Host "Started with PID: `$(`$process.Id)"
"@

$startScriptPath = "$AppDir\Start-Node.ps1"
Set-Content -Path $startScriptPath -Value $startScript -Encoding UTF8

# Start using PowerShell with -NoExit to keep running after SSH ends
$powershell = "powershell.exe"
$args = "-NoProfile -ExecutionPolicy Bypass -File `"$startScriptPath`" -NoExit"

# Start in detached mode
$processInfo = New-Object System.Diagnostics.ProcessStartInfo
$processInfo.FileName = $powershell
$processInfo.Arguments = $args
$processInfo.UseShellExecute = $false
$processInfo.WorkingDirectory = $AppDir
$processInfo.CreateNoWindow = $true

$proc = [System.Diagnostics.Process]::Start($processInfo)

Write-Host "  Launcher started, waiting for Node.js..."
Start-Sleep -Seconds 15

# Step 6: Health check
Write-Host ""
Write-Host "[6/6] Health check..." -ForegroundColor Cyan

$healthy = $false
for ($i = 1; $i -le 30; $i++) {
    try {
        $response = Invoke-WebRequest -Uri "http://127.0.0.1:3000/api/version" -UseBasicParsing -TimeoutSec 5
        if ($response.StatusCode -eq 200) {
            $version = $response.Content | ConvertFrom-Json
            Write-Host "  OK! Version: $($version.version)" -ForegroundColor Green
            $healthy = $true
            break
        }
    } catch {
        Write-Host "  Attempt $i/30..."
        Start-Sleep -Seconds 2
    }
}

if (-not $healthy) {
    Write-Host "ERROR: Health check failed!" -ForegroundColor Red
    exit 1
}

# Create .version file
Set-Content -Path "$AppDir\.version" -Value $newVersion -Encoding UTF8

Write-Host ""
Write-Host "========================================"
Write-Host "  Deploy Complete!"
Write-Host "========================================"
Write-Host "Version: $newVersion"
Write-Host "Node.js will keep running after SSH disconnect"
Write-Host "Time: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
Write-Host "========================================"

# Cleanup
& git config --local --unset credential.helper 2>&1 | Out-Null

exit 0
